//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ispan_LinQPractice_WinApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_order_customer
    {
        public int 訂單代號 { get; set; }
        public Nullable<System.DateTime> 訂單日期 { get; set; }
        public string 客戶代號 { get; set; }
        public string 公司名稱 { get; set; }
        public Nullable<int> 員工代號 { get; set; }
        public Nullable<int> 運輸代號 { get; set; }
        public int 產品代號 { get; set; }
        public short 數量 { get; set; }
        public decimal 單價 { get; set; }
    }
}
