//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ispan_LinQPractice_WinApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class 折扣試算檢視表
    {
        public string 折扣數 { get; set; }
        public int 產品代號 { get; set; }
        public string 產品名稱 { get; set; }
        public Nullable<decimal> 原價 { get; set; }
        public Nullable<decimal> 折扣價 { get; set; }
    }
}
